name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install stylua
              uses: JohnnyMorganz/stylua-action@v4
              with:
                  version: latest
                  token: ${{ secrets.GITHUB_TOKEN }}
                  args: false
            - name: Run lint
              run: make lint

    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Neovim
              uses: rhysd/action-setup-vim@v1
              with:
                  neovim: true
                  version: stable
            - name: Install ripgrep
              run: sudo apt-get update && sudo apt-get install -y ripgrep
            - name: Run tests
              run: make test

    docs:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      name: Docs
      if: ${{ github.ref == 'refs/heads/main' }}
      steps:
        - uses: actions/checkout@v4
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
        - name: panvimdoc
          uses: kdheepak/panvimdoc@main
          with:
            vimdoc: slopcode
            dedupsubheadings: false
            version: "NVIM v0.12.3"
        - uses: stefanzweifel/git-auto-commit-action@v5
          with:
            commit_message: "chore(doc): auto generate docs"
            commit_user_name: "github-actions[bot]"
            commit_user_email: "github-actions[bot]@users.noreply.github.com"
            commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
            commit_options: "--no-verify"
